Fixes for compressPtclID. Now a local dictionary within method is used to reindex ptcl objects and then assigned to the self.ptclC within the structure. Prevents changing the self.ptclC in place and changing size of dictionary
Works with Travis replicate script.

Only error now is presumably associated with other changes in branch.

Traceback (most recent call last):
  File "../scripts/replicate.py", line 117, in <module>
    main()
  File "../scripts/replicate.py", line 114, in main
    f_rep.write_gro(options.dir_id,options.output_id )
  File "/Users/ssides/ztools/PRoSpeCT/tools/src/structureContainer.py", line 914, in write_gro
    import gromacs
ImportError: No module named gromacs
ParallelMsgr destructor called